
# MAKEFILE GENERATED BY PTT
# https://github.com/KubaBoi/ptt

NAME=kelp_temp
OBJFILES=$(NAME).o 

CC=g++
CFLAGS= -v

%.o : %.c 
	$(CC) $(CFLAGS) -c $<

all: $(NAME)

dep:
	$(CC) -MM *.c >dep.list

-include dep.list

$(NAME): $(OBJFILES)
	$(CC) $(CFLAGS) $(OBJFILES) -o $@
	